name: C/C++ CI

on: [workflow_dispatch]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: carlosperate/arm-linux-gnueabi-gcc@v1
    - run:  arm-linux-gnueabi-gcc -static -march=armv7-a /tgcrypto/tgcrypto.c -o main      
           
           
