name: C/C++ CI

on: [workflow_dispatch]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: file tree
      run: tree -a
    - uses: carlosperate/arm-none-eabi-gcc-action@v1
    - name: Compile
      run:  arm-none-eabi-gcc -static -march=armv7-a /tgcrypto/tgcrypto.c -o main      
           
           
