name: C/C++ CI

on: [workflow_dispatch]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: carlosperate/arm-none-eabi-gcc-action@v1
    - run:  arm-none-eabi-gcc -static -march=armv7-a /tgcrypto/tgcrypto.c -o main      
           
           
