name: C/C++ CI

on: [workflow_dispatch]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: file tree
      run: tree -a
    - uses: actions/setup-python@v5
      with:
        python-version: '3.8-dev'
    - uses: carlosperate/arm-none-eabi-gcc-action@v1
    - name: Compile
      run:  arm-none-eabi-gcc -static -march=armv7-a tgcrypto/tgcrypto.c -o main      
           
           
